spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          coordinator_class: jdbc
logging:
  level:
    root: INFO
    com.exist: DEBUG
  file:
    name: logs/application.log